leftnav:
- identifier: d1de24cf-e1fb-4bca-8312-83de813db6bb
  name: Hello
  url: /pages/jkanckaj
  weight: 10
- identifier: 91c9d49d-4e60-4168-8b49-d130adfb4f8f
  name: nice
  url: /pages/knqkfjnkjn
  weight: 20
